[workspace]
resolver = "3"
members = [ "calculator","parser-combinator", "calculator"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
