[package]
name = "calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
parser-combinator = { path = "../parser-combinator" }
