[package]
name = "calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["debug", "fira-sans", "webgl"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
#iced.workspace = true
#iced.features = ["webgl", "fira-sans"]
